In [ ]:
# tablas base de datos proyecto paloma

In [1]:
"""
CREATE TABLE ENERGIA (
    SISTEMA VARCHAR(50),
    TARIFA VARCHAR(50),
    CIA VARCHAR(50),
    mes DATE,
    FEE VARCHAR(50),
    P1_e FLOAT,
    P2_e FLOAT,
    P3_e FLOAT,
    P4_e FLOAT,
    P5_e FLOAT,
    P6_e FLOAT
);

CREATE TABLE POTENCIA (
    Sistema VARCHAR(50),
    CIA VARCHAR(50),
    PRODUCTO VARCHAR(50),
    PRODUCTO_CIA VARCHAR(50),
    Tarifa VARCHAR(50),
    P1 FLOAT,
    P2 FLOAT,
    P3 FLOAT,
    P4 FLOAT,
    P5 FLOAT,
    P6 FLOAT
);

CREATE TABLE Fijo (
    sistema VARCHAR(50),
    cia VARCHAR(50),
    producto VARCHAR(50),
    producto_cia VARCHAR(50),
    tarifa VARCHAR(50),
    fee VARCHAR(50),
    P1 FLOAT,
    P2 FLOAT,
    P3 FLOAT,
    P4 FLOAT,
    P5 FLOAT,
    P6 FLOAT,
    P1_e FLOAT,
    P2_e FLOAT,
    P3_e FLOAT,
    P4_e FLOAT,
    P5_e FLOAT,
    P6_e FLOAT
);

CREATE TABLE Usuario (
    ID_Usuario SERIAL PRIMARY KEY,
    Email VARCHAR(50),
    Contraseña VARCHAR(20),
    Rol VARCHAR(50)
);

CREATE TABLE Cliente (
    CUPS VARCHAR(50) PRIMARY KEY,
    ID_Usuario INT,
    Nombre_cliente VARCHAR(50),
    Dirección VARCHAR(50),
    FOREIGN KEY (ID_Usuario) REFERENCES Usuario(ID_Usuario)
);

CREATE TABLE sips (
    ID_sips SERIAL PRIMARY KEY,
    tarifa VARCHAR(20),
    Consumo_anual FLOAT,
    ca_p1 FLOAT,
    ca_p2 FLOAT,
    ca_p3 FLOAT,
    ca_p4 FLOAT,
    ca_p5 FLOAT,
    ca_p6 FLOAT,
    CUPS VARCHAR (50),
    Municipio VARCHAR(50),
    Provincia VARCHAR(50),
    Codigo_postal VARCHAR(50),
    Distribuidora_actual VARCHAR(50)
);

CREATE TABLE Consumo_Energia (
    ID_Consumo_Energia SERIAL PRIMARY KEY,
    ID_Factura INT,
    E1 FLOAT,
    E2 FLOAT,
    E3 FLOAT,
    E4 FLOAT,
    E5 FLOAT,
    E6 FLOAT,
    Consumo_Anual_Total_KW FLOAT,
    Consumo_Factura_Actual_Total_KWh FLOAT,
    Total_Pago_Factura FLOAT,
    Total_Pago_Anual FLOAT
);

CREATE TABLE Consumo_potencia (
    ID_Consumo_Potencia SERIAL PRIMARY KEY,
    ID_Factura INT,
    P1 FLOAT,
    P2 FLOAT,
    P3 FLOAT,
    P4 FLOAT,
    P5 FLOAT,
    P6 FLOAT,
    Consumo_Anual_Total_KW FLOAT,
    Consumo_Factura_Actual_Total_KWh FLOAT,
    Total_Pago_Factura FLOAT,
    Total_Pago_Anual FLOAT
);

CREATE TABLE Factura (
    ID_Factura SERIAL PRIMARY KEY,
    ID_sips INT,
    ID_Consumo_Energia INT,
    ID_Consumo_Potencia INT,
    CUPS VARCHAR(30),
    Fecha_Factura DATE,
    Importe_Total_Factura FLOAT,
    Días_facturación INT,
    Energia_reactiva FLOAT,
    Impuesto_eléctrico FLOAT,
    Alquiler_equipo FLOAT,
    Otros_costes FLOAT,
    Descuento FLOAT,
    FOREIGN KEY (ID_sips) REFERENCES sips(ID_sips),
    FOREIGN KEY (ID_Consumo_Energia) REFERENCES Consumo_Energia(ID_Consumo_Energia),
    FOREIGN KEY (ID_Consumo_Potencia) REFERENCES Consumo_potencia(ID_Consumo_Potencia),
    FOREIGN KEY (CUPS) REFERENCES Cliente(CUPS)
);

CREATE TABLE Propuesta (
    ID_Propuesta SERIAL PRIMARY KEY,
    ID_Usuario INT,
    ID_Factura INT,
    ID_Cia INT,
    ID_sips INT UNIQUE,
    Detalles_Propuesta VARCHAR(50),
    Total_Pago_Propuesto FLOAT,
    FOREIGN KEY (ID_Factura) REFERENCES Factura(ID_Factura)
);


"""

'\nCREATE TABLE INDEXADO1 (\n    ID_Indexado1 SERIAL PRIMARY KEY,\n    Sistema VARCHAR(20),\n    Tarifa VARCHAR(20),\n    Cia VARCHAR(20),\n    Mes DATE,\n    fee VARCHAR(20),\n    P1punto FLOAT,\n    P2punto FLOAT,\n    P3punto FLOAT,\n    P4punto FLOAT,\n    P5punto FLOAT,\n    P6punto FLOAT\n);\n\nCREATE TABLE INDEXADO2 (\n    ID_Indexado2 SERIAL PRIMARY KEY,\n    Sistema VARCHAR(20),\n    Cia VARCHAR(20),\n    Producto VARCHAR(20),\n    Producto_Cia VARCHAR(20),\n    Tarifa VARCHAR(20),\n    P1 FLOAT,\n    P2 FLOAT,\n    P3 FLOAT,\n    P4 FLOAT,\n    P5 FLOAT,\n);\n\nCREATE TABLE Usuario (\n    ID_Usuario SERIAL PRIMARY KEY,\n    Email VARCHAR(50),\n    Contraseña VARCHAR(20),\n    Rol VARCHAR(50)\n);\n\nCREATE TABLE Cliente (\n    CUPS VARCHAR(50) PRIMARY KEY,\n    ID_Usuario INT,\n    Nombre_cliente VARCHAR(30),\n    Dirección VARCHAR(30),\n    FOREIGN KEY (ID_Usuario) REFERENCES Usuario(ID_Usuario)\n);\n\nCREATE TABLE sips (\n    ID_sips SERIAL PRIMARY KEY,\n    tarifa VARCHAR(20),\n    Consumo_anual FLOAT,\n    ca_p1 FLOAT,\n    ca_p2 FLOAT,\n    ca_p3 FLOAT,\n    ca_p4 FLOAT,\n    ca_p5 FLOAT,\n    ca_p6 FLOAT,\n    CUPS VARCHAR (50),\n    Municipio VARCHAR(50),\n    Provincia VARCHAR(50),\n    Codigo_postal VARCHAR(50),\n    Distribuidora_actual VARCHAR(50),\n    FOREIGN KEY (CUPS) REFERENCES Cliente(CUPS)\n);\n\nCREATE TABLE Consumo_Energia (\n    ID_Consumo_Energia SERIAL PRIMARY KEY,\n    ID_Factura INT,\n    E1 FLOAT,\n    E2 FLOAT,\n    E3 FLOAT,\n    E4 FLOAT,\n    E5 FLOAT,\n    E6 FLOAT,\n    Consumo_Anual_Total_KW FLOAT,\n    Consumo_Factura_Actual_Total_KWh FLOAT,\n    Total_Pago_Factura FLOAT,\n    Total_Pago_Anual FLOAT,\n    FOREIGN KEY (ID_Factura) REFERENCES Factura(ID_Factura)\n);\n\nCREATE TABLE Consumo_potencia (\n    ID_Consumo_Potencia SERIAL PRIMARY KEY,\n    ID_Factura INT,\n    P1 FLOAT,\n    P2 FLOAT,\n    P3 FLOAT,\n    P4 FLOAT,\n    P5 FLOAT,\n    P6 FLOAT,\n    Consumo_Anual_Total_KW FLOAT,\n    Consumo_Factura_Actual_Total_KWh FLOAT,\n    Total_Pago_Factura FLOAT,\n    Total_Pago_Anual FLOAT,\n    FOREIGN KEY (ID_Factura) REFERENCES Factura(ID_Factura)\n);\n\nCREATE TABLE Factura (\n    ID_Factura SERIAL PRIMARY KEY,\n    CUPS VARCHAR(30),\n    Fecha_Factura DATE,\n    Importe_Total_Factura FLOAT,\n    Días_facturación INT,\n    Energia_reactiva FLOAT,\n    Impuesto_eléctrico FLOAT,\n    Alquiler_equipo FLOAT,\n    Otros_costes FLOAT,\n    Descuento FLOAT,\n    FOREIGN KEY (CUPS) REFERENCES Cliente(CUPS)\n);\n\nCREATE TABLE Propuesta (\n    ID_Propuesta SERIAL PRIMARY KEY,\n    ID_Usuario INT,\n    ID_Factura INT,\n    ID_Cia INT,\n    ID_sips INT UNIQUE,\n    Detalles_Propuesta VARCHAR(50),\n    Total_Pago_Propuesto FLOAT,\n    FOREIGN KEY (ID_Usuario) REFERENCES Usuario(ID_Usuario),\n    FOREIGN KEY (ID_Factura) REFERENCES Factura(ID_Factura),\n    FOREIGN KEY (ID_Cia) REFERENCES Comercializadora(ID_Cia)\n);\n\nCREATE TABLE Comercializadora (\n    ID_Cia SERIAL PRIMARY KEY,\n    Comercializadora VARCHAR(50),\n    Sistema VARCHAR(20),\n    Tarifa VARCHAR(20),\n    ID_Cia_Fijo_Energia INT,\n    ID_Cia_Fijo_Potencia INT,\n    ID_Cia_indexado_energia INT,\n    ID_Cia_indexado_potencia INT,\n    FOREIGN KEY (ID_Cia_Fijo_Energia) REFERENCES Precio_Fijo_Energia(ID_Comercializadora),\n    FOREIGN KEY (ID_Cia_Fijo_Potencia) REFERENCES Precio_Fijo_Potencia(ID_Comercializadora),\n    FOREIGN KEY (ID_Cia_indexado_energia) REFERENCES Precio_indexado_energia(ID_Comercializadora),\n    FOREIGN KEY (ID_Cia_indexado_potencia) REFERENCES Precio_indexado_potencia(ID_Comercializadora)\n);\n\n\n\n\n\n\n\n alter table sips\n  add constraint fk_sips foreign key\n (id_sips) references Propuesta (id_sips);\n\n'